language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
install: 
  - "pip install -r requirements.testing.txt"
  - "pip install coveralls"
# command to run tests
script: "coverage run --source=ommongo setup.py test"
# coveralls
after_success:
  coveralls